INSERT INTO estados(e_id,e_nombre) VALUES (1,'Aguascalientes');
INSERT INTO estados(e_id,e_nombre) VALUES (2,'Baja California');
INSERT INTO estados(e_id,e_nombre) VALUES (3,'Baja California Sur');
INSERT INTO estados(e_id,e_nombre) VALUES (4,'Campeche');
INSERT INTO estados(e_id,e_nombre) VALUES (5,'Coahuila de Zaragoza');
INSERT INTO estados(e_id,e_nombre) VALUES (6,'Colima');
INSERT INTO estados(e_id,e_nombre) VALUES (7,'Chiapas');
INSERT INTO estados(e_id,e_nombre) VALUES (8,'Chihuahua');
INSERT INTO estados(e_id,e_nombre) VALUES (9,'Ciudad de México');
INSERT INTO estados(e_id,e_nombre) VALUES (10,'Durango');
INSERT INTO estados(e_id,e_nombre) VALUES (11,'Guanajuato');
INSERT INTO estados(e_id,e_nombre) VALUES (12,'Guerrero');
INSERT INTO estados(e_id,e_nombre) VALUES (13,'Hidalgo');
INSERT INTO estados(e_id,e_nombre) VALUES (14,'Jalisco');
INSERT INTO estados(e_id,e_nombre) VALUES (15,'México');
INSERT INTO estados(e_id,e_nombre) VALUES (16,'Michoacán de Ocampo');
INSERT INTO estados(e_id,e_nombre) VALUES (17,'Morelos');
INSERT INTO estados(e_id,e_nombre) VALUES (18,'Nayarit');
INSERT INTO estados(e_id,e_nombre) VALUES (19,'Nuevo León');
INSERT INTO estados(e_id,e_nombre) VALUES (20,'Oaxaca');
INSERT INTO estados(e_id,e_nombre) VALUES (21,'Puebla');
INSERT INTO estados(e_id,e_nombre) VALUES (22,'Querétaro');
INSERT INTO estados(e_id,e_nombre) VALUES (23,'Quintana Roo');
INSERT INTO estados(e_id,e_nombre) VALUES (24,'San Luis Potosí');
INSERT INTO estados(e_id,e_nombre) VALUES (25,'Sinaloa');
INSERT INTO estados(e_id,e_nombre) VALUES (26,'Sonora');
INSERT INTO estados(e_id,e_nombre) VALUES (27,'Tabasco');
INSERT INTO estados(e_id,e_nombre) VALUES (28,'Tamaulipas');
INSERT INTO estados(e_id,e_nombre) VALUES (29,'Tlaxcala');
INSERT INTO estados(e_id,e_nombre) VALUES (30,'Veracruz de Ignacio de la Llave');
INSERT INTO estados(e_id,e_nombre) VALUES (31,'Yucatán');
INSERT INTO estados(e_id,e_nombre) VALUES (32,'Zacatecas');
